### ISSUE TITLE
Portfolio Ideas

### ISSUE THREAD

**Issue by bkill16** [bkill16/cse290#1]
Planning to create a personal portfolio website.

- [x] Body background should be #F0F0F0
- [x] Header background should be #1E1E1E with white text
- [x] The “My Resume” and “View Source Code” and “View Website” links should look like buttons. 
Background color should be #F0A500 with a text color of white. On hover, the background should be #FFB800 with a text color of white
- [x] Footer background should be #1E1E1E with white text
- [x] Hero section content should be center aligned
- [x] Skills section header should be center aligned
- [x] Projects section header should be center aligned
- [x] Projects section layout should be the project title, image, and links to the left and the description on the right (HTML is set up with a left class and a right class)
- [x] Add padding, margin, line height, increase font sizes, etc to improve overall readability and aesthetic

**Comment by dallinmoak** [comment]
ok imma start a branch to work on task "Body background should be #F0F0F0" and "Header background should be #1E1E1E with white text"

**Comment by dallinmoak** [comment]
actually, nvm, @bkill16 it looks like you don't have a skeleton html file up yet on your main branch. maybe i'll wait till you have one..

**Comment by bkill16** [comment]
Oh oops haha. @dallinmoak i got it merged. Thanks!
